import datetime
import time

import pymysql
import qdarkstyle
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QMessageBox,
                             QDesktopWidget, QWidget)


def show_inserted_popup():
    message = QMessageBox()
    message.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
    message.setWindowTitle("Success!")
    message.setText("Data is successfully inserted.")
    message.setIcon(QMessageBox.Information)
    x = message.exec_()


def duplicate_entry():
    message = QMessageBox()
    message.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
    message.setWindowTitle("Oops!")
    message.setText("Duplicate ID, please retry.")
    message.setIcon(QMessageBox.Information)
    x = message.exec_()


class Ui_signup(QWidget):
    def setupUi(self, signup):
        self.signup = signup
        signup.setObjectName("signup")
        signup.resize(400, 650)
        signup.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/adduser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        signup.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(signup)
        self.centralwidget.setObjectName("centralwidget")
        self.Submit = QtWidgets.QPushButton(self.centralwidget)
        self.Submit.setGeometry(QtCore.QRect(188, 576, 180, 25))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.Submit.setFont(font)
        self.Submit.setStyleSheet("")
        self.Submit.setObjectName("SignUp")
        self.IDLine = QtWidgets.QLineEdit(self.centralwidget)
        self.IDLine.setGeometry(QtCore.QRect(188, 34, 180, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IDLine.sizePolicy().hasHeightForWidth())
        self.IDLine.setSizePolicy(sizePolicy)
        self.IDLine.setStyleSheet(open("./qss/lineEdit.qss", "r").read())
        self.IDLine.setObjectName("IDLine")
        self.F_NOLine = QtWidgets.QLineEdit(self.centralwidget)
        self.F_NOLine.setGeometry(QtCore.QRect(188, 70, 180, 21))
        self.F_NOLine.setStyleSheet(open("./qss/lineEdit.qss", "r").read())
        self.F_NOLine.setObjectName("F_NOLine")
        self.EmployeeIDLine = QtWidgets.QLineEdit(self.centralwidget)
        self.EmployeeIDLine.setGeometry(QtCore.QRect(188, 106, 180, 21))
        self.EmployeeIDLine.setStyleSheet(open("./qss/lineEdit.qss", "r").read())
        self.EmployeeIDLine.setObjectName("EmployeeIDLine")
        self.EmployeeNameLine = QtWidgets.QLineEdit(self.centralwidget)
        self.EmployeeNameLine.setGeometry(QtCore.QRect(188, 142, 180, 21))
        self.EmployeeNameLine.setStyleSheet(open("./qss/lineEdit.qss", "r").read())
        self.EmployeeNameLine.setObjectName("EmployeeNameLine")
        self.DepartmentLine = QtWidgets.QLineEdit(self.centralwidget)
        self.DepartmentLine.setGeometry(QtCore.QRect(188, 178, 180, 21))
        self.DepartmentLine.setStyleSheet(open("./qss/lineEdit.qss", "r").read())
        self.DepartmentLine.setObjectName("DepartmentLine")
        self.RoleLine = QtWidgets.QLineEdit(self.centralwidget)
        self.RoleLine.setGeometry(QtCore.QRect(188, 214, 180, 21))
        self.RoleLine.setStyleSheet(open("./qss/lineEdit.qss", "r").read())
        self.RoleLine.setObjectName("RoleLine")
        self.ShiftPatternLine = QtWidgets.QLineEdit(self.centralwidget)
        self.ShiftPatternLine.setGeometry(QtCore.QRect(188, 250, 180, 21))
        self.ShiftPatternLine.setStyleSheet(open("./qss/lineEdit.qss", "r").read())
        self.ShiftPatternLine.setObjectName("ShiftPatternLine")
        self.MobileLine = QtWidgets.QLineEdit(self.centralwidget)
        self.MobileLine.setGeometry(QtCore.QRect(188, 286, 180, 21))
        self.MobileLine.setStyleSheet(open("./qss/lineEdit.qss", "r").read())
        self.MobileLine.setObjectName("MobileLine")
        self.RequestDateLine = QtWidgets.QLineEdit(self.centralwidget)
        self.RequestDateLine.setGeometry(QtCore.QRect(188, 322, 180, 21))
        self.RequestDateLine.setStyleSheet(open("./qss/lineEdit.qss", "r").read())
        self.RequestDateLine.setObjectName("RequestDateLine")
        self.RequestTypeLine = QtWidgets.QLineEdit(self.centralwidget)
        self.RequestTypeLine.setGeometry(QtCore.QRect(188, 358, 180, 21))
        self.RequestTypeLine.setStyleSheet(open("./qss/lineEdit.qss", "r").read())
        self.RequestTypeLine.setObjectName("RequestTypeLine")
        self.VehicleTypeLine = QtWidgets.QLineEdit(self.centralwidget)
        self.VehicleTypeLine.setGeometry(QtCore.QRect(188, 394, 180, 21))
        self.VehicleTypeLine.setStyleSheet(open("./qss/lineEdit.qss", "r").read())
        self.VehicleTypeLine.setObjectName("VehicleTypeLine")
        self.VehicleModelLine = QtWidgets.QLineEdit(self.centralwidget)
        self.VehicleModelLine.setGeometry(QtCore.QRect(188, 430, 180, 21))
        self.VehicleModelLine.setStyleSheet(open("./qss/lineEdit.qss", "r").read())
        self.VehicleModelLine.setObjectName("VehicleModelLine")
        self.VehiclePlateNumberLine = QtWidgets.QLineEdit(self.centralwidget)
        self.VehiclePlateNumberLine.setGeometry(QtCore.QRect(188, 466, 180, 21))
        self.VehiclePlateNumberLine.setStyleSheet(open("./qss/lineEdit.qss", "r").read())
        self.VehiclePlateNumberLine.setObjectName("VehiclePlateNumberLine")
        self.VehicleColorLine = QtWidgets.QLineEdit(self.centralwidget)
        self.VehicleColorLine.setGeometry(QtCore.QRect(188, 502, 180, 21))
        self.VehicleColorLine.setStyleSheet(open("./qss/lineEdit.qss", "r").read())
        self.VehicleColorLine.setObjectName("VehicleColorLine")
        self.EmployeeNameText = QtWidgets.QLabel(self.centralwidget)
        self.EmployeeNameText.setGeometry(QtCore.QRect(52, 142, 125, 19))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.EmployeeNameText.setFont(font)
        self.EmployeeNameText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.EmployeeNameText.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.EmployeeNameText.setObjectName("EmployeeNameText")
        self.IDText = QtWidgets.QLabel(self.centralwidget)
        self.IDText.setGeometry(QtCore.QRect(141, 34, 37, 19))
        self.IDText.setFont(font)
        self.IDText.setStyleSheet("")
        self.IDText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.IDText.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.IDText.setObjectName("IDText")
        self.F_NOText = QtWidgets.QLabel(self.centralwidget)
        self.F_NOText.setGeometry(QtCore.QRect(119, 70, 59, 19))
        self.F_NOText.setFont(font)
        self.F_NOText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.F_NOText.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.F_NOText.setObjectName("F_NOText")
        self.EmployeeIDText = QtWidgets.QLabel(self.centralwidget)
        self.EmployeeIDText.setGeometry(QtCore.QRect(69, 106, 109, 19))
        self.EmployeeIDText.setFont(font)
        self.EmployeeIDText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.EmployeeIDText.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.EmployeeIDText.setObjectName("EmployeeIDText")
        self.VehicleColorText = QtWidgets.QLabel(self.centralwidget)
        self.VehicleColorText.setGeometry(QtCore.QRect(62, 502, 115, 19))
        self.VehicleColorText.setFont(font)
        self.VehicleColorText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.VehicleColorText.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.VehicleColorText.setObjectName("VehicleColorText")
        self.DepartmentText = QtWidgets.QLabel(self.centralwidget)
        self.DepartmentText.setGeometry(QtCore.QRect(83, 178, 97, 19))
        self.DepartmentText.setFont(font)
        self.DepartmentText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DepartmentText.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.DepartmentText.setObjectName("DepartmentText")
        self.RoleText = QtWidgets.QLabel(self.centralwidget)
        self.RoleText.setGeometry(QtCore.QRect(125, 212, 53, 19))
        self.RoleText.setFont(font)
        self.RoleText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.RoleText.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.RoleText.setObjectName("RoleText")
        self.ShiftPatternText = QtWidgets.QLabel(self.centralwidget)
        self.ShiftPatternText.setGeometry(QtCore.QRect(73, 250, 103, 19))
        self.ShiftPatternText.setFont(font)
        self.ShiftPatternText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ShiftPatternText.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ShiftPatternText.setObjectName("ShiftPatternText")
        self.MobileText = QtWidgets.QLabel(self.centralwidget)
        self.MobileText.setGeometry(QtCore.QRect(86, 286, 89, 19))
        self.MobileText.setFont(font)
        self.MobileText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MobileText.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.MobileText.setObjectName("MobileText")
        self.RequestDateText = QtWidgets.QLabel(self.centralwidget)
        self.RequestDateText.setGeometry(QtCore.QRect(67, 322, 109, 19))
        self.RequestDateText.setFont(font)
        self.RequestDateText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.RequestDateText.setTextFormat(QtCore.Qt.AutoText)
        self.RequestDateText.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.RequestDateText.setObjectName("RequestDateText")
        self.RequestTypeText = QtWidgets.QLabel(self.centralwidget)
        self.RequestTypeText.setGeometry(QtCore.QRect(51, 358, 125, 19))
        self.RequestTypeText.setFont(font)
        self.RequestTypeText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.RequestTypeText.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.RequestTypeText.setObjectName("RequestTypeText")
        self.VehicleTypeText = QtWidgets.QLabel(self.centralwidget)
        self.VehicleTypeText.setGeometry(QtCore.QRect(71, 394, 105, 19))
        self.VehicleTypeText.setFont(font)
        self.VehicleTypeText.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.VehicleTypeText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.VehicleTypeText.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.VehicleTypeText.setObjectName("VehicleTypeText")
        self.VehicleModelText = QtWidgets.QLabel(self.centralwidget)
        self.VehicleModelText.setGeometry(QtCore.QRect(61, 430, 115, 19))
        self.VehicleModelText.setFont(font)
        self.VehicleModelText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.VehicleModelText.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.VehicleModelText.setObjectName("VehicleModelText")
        self.VehiclePlateNumberText = QtWidgets.QLabel(self.centralwidget)
        self.VehiclePlateNumberText.setGeometry(QtCore.QRect(20, 466, 157, 19))
        self.VehiclePlateNumberText.setFont(font)
        self.VehiclePlateNumberText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.VehiclePlateNumberText.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.VehiclePlateNumberText.setObjectName("VehiclePlateNumberText")
        self.Options = QtWidgets.QComboBox(self.centralwidget)
        self.Options.setGeometry(QtCore.QRect(188, 538, 180, 21))
        self.Options.setFont(font)
        self.Options.setObjectName("Options")
        self.Options.addItem("")
        signup.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(signup)
        self.statusbar.setObjectName("statusbar")
        signup.setStatusBar(self.statusbar)

        self.retranslateUi(signup)
        QtCore.QMetaObject.connectSlotsByName(signup)

        self.Submit.clicked.connect(self.insertData)
        self.Options.addItem("VVIP")
        self.Options.addItem("Special Need")
        self.Options.addItem("Zone A")
        self.Options.addItem("Zone B")
        self.Options.addItem("Visitors")

    def retranslateUi(self, signup):
        _translate = QtCore.QCoreApplication.translate
        signup.setWindowTitle(_translate("signup", "signup"))
        self.Submit.setText(_translate("signup", "Submit"))
        self.Submit.setStatusTip(_translate("signup", "Register Vehicle"))
        self.Submit.setShortcut(_translate("signup", "Return"))
        self.EmployeeNameText.setText(_translate("signup", "Employee Name"))
        self.EmployeeNameText.setStatusTip(_translate("signup", "Employee Name"))
        self.IDText.setText(_translate("signup", "ID"))
        self.IDText.setStatusTip(_translate("signup", "ID"))
        self.F_NOText.setText(_translate("signup", "F_NO"))
        self.F_NOText.setStatusTip(_translate("signup", "F_NO"))
        self.EmployeeIDText.setText(_translate("signup", "Employee ID"))
        self.EmployeeIDText.setStatusTip(_translate("signup", "Employee ID"))
        self.VehicleColorText.setText(_translate("signup", "Vehicle Color"))
        self.VehicleColorText.setStatusTip(_translate("signup", "Vehicle Color"))
        self.DepartmentText.setText(_translate("signup", "Department"))
        self.DepartmentText.setStatusTip(_translate("signup", "Department"))
        self.RoleText.setText(_translate("signup", "Role"))
        self.RoleText.setStatusTip(_translate("signup", "Role"))
        self.ShiftPatternText.setText(_translate("signup", "Shift Pattern"))
        self.ShiftPatternText.setStatusTip(_translate("signup", "Shift Pattern"))
        self.MobileText.setText(_translate("signup", "Mobile No"))
        self.MobileText.setStatusTip(_translate("signup", "Mobile No"))
        self.RequestDateText.setText(_translate("signup", "Request Date"))
        self.RequestDateText.setStatusTip(_translate("signup", "Request Date"))
        self.RequestTypeText.setText(_translate("signup", "Request Type"))
        self.RequestTypeText.setStatusTip(_translate("signup", "Request Type"))
        self.VehicleTypeText.setText(_translate("signup", "Vehicle Type"))
        self.VehicleTypeText.setStatusTip(_translate("signup", "Vehicle Type"))
        self.VehicleModelText.setText(_translate("signup", "Vehicle Model"))
        self.VehicleModelText.setStatusTip(_translate("signup", "Vehicle Model"))
        self.VehiclePlateNumberText.setText(_translate("signup", "Vehicle Plate Number"))
        self.VehiclePlateNumberText.setStatusTip(_translate("signup", "Vehicle Plate Number"))
        self.Options.setItemText(0, _translate("MainWindow", "---Select---"))
        self.Options.setStatusTip(_translate("MainWindow", "Options"))

    def insertData(self):
        try:
            con = pymysql.connect(host='localhost', user='root', port=3306, password='',
                                  db='register')
            cur = con.cursor()
            unix = int(time.time())
            hour = str(datetime.datetime.fromtimestamp(unix).strftime('%H'))
            timestamp = str(datetime.datetime.fromtimestamp(unix).strftime('%Y-%m-%d %H:%M:%S'))
            area = self.Options.currentText()
            cur.execute("INSERT INTO sps_data(ID, F_NO, employee_id, employee_name, department, role, shift_pattern, "
                        "mobile, request_date, request_type, vehicle_type, vehicle_model, vehicle_plate_number, "
                        "vehicle_color, hour, timestamp, area) "
                        "VALUES('%s', '%s', '%s','%s','%s','%s', '%s', '%s','%s','%s','%s','%s','%s','%s','%s', '%s',"
                        "'%s')" %
                        (''.join(self.IDLine.text()),
                         ''.join(self.F_NOLine.text()),
                         ''.join(self.EmployeeIDLine.text()),
                         ''.join(self.EmployeeNameLine.text()),
                         ''.join(self.DepartmentLine.text()),
                         ''.join(self.RoleLine.text()),
                         ''.join(self.ShiftPatternLine.text()),
                         ''.join(self.MobileLine.text()),
                         ''.join(self.RequestDateLine.text()),
                         ''.join(self.RequestTypeLine.text()),
                         ''.join(self.VehicleTypeLine.text()),
                         ''.join(self.VehicleModelLine.text()),
                         ''.join(self.VehiclePlateNumberLine.text()),
                         ''.join(self.VehicleColorLine.text()), hour, timestamp, area))

            con.commit()
            show_inserted_popup()

        except pymysql.IntegrityError as err:
            duplicate_entry()
            return None

    def center(self):
        qr = self.signup.frameGeometry()
        cp = QDesktopWidget().availableGeometry().center()
        qr.moveCenter(cp)
        self.signup.move(qr.topLeft())


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    signup = QtWidgets.QMainWindow()
    ui = Ui_signup()
    ui.setupUi(signup)
    signup.show()
    sys.exit(app.exec_())
