import os

import pandas as pd
import pyqtgraph as pg
import qdarkstyle
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QGraphicsObject

os.environ['PYQTGRAPH_QT_LIB'] = 'PyQt5'


def show_empty_popup():
    message = QMessageBox()
    message.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
    message.setWindowTitle("Hi")
    message.setText("VVIP is empty, please proceed.")
    message.setIcon(QMessageBox.Information)
    message.exec_()


def show_full_popup():
    message = QMessageBox()
    message.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
    message.setWindowTitle("Oops")
    message.setText("VVIP is full, please proceed to next.")
    message.setIcon(QMessageBox.Information)
    message.exec_()


def show_inserted_popup():
    message = QMessageBox()
    message.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
    message.setWindowTitle("Success")
    message.setText("Data is successfully inserted.")
    message.setIcon(QMessageBox.Information)
    message.exec_()


class Ui_Overview(QGraphicsObject):

    def overviewUi(self, Overview):
        self.overview = Overview
        Overview.setObjectName("MainWindow")
        Overview.resize(1300, 840)
        Overview.setFocusPolicy(QtCore.Qt.WheelFocus)
        Overview.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/combochart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Overview.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Overview)
        self.centralwidget.setObjectName("centralwidget")
        self.SiteCombox = QtWidgets.QComboBox(self.centralwidget)
        self.SiteCombox.setGeometry(QtCore.QRect(30, 140, 290, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SiteCombox.setFont(font)
        self.SiteCombox.setObjectName("SiteCombox")
        self.SiteCombox.addItem("")
        self.VVIPbar = QtWidgets.QProgressBar(self.centralwidget)
        self.VVIPbar.setGeometry(QtCore.QRect(30, 242, 280, 10))
        self.VVIPbar.setStyleSheet(open("./qss/0_to_99%.qss", "r").read())
        self.VVIPbar.setProperty("value", 0)
        self.VVIPbar.setAlignment(QtCore.Qt.AlignCenter)
        self.VVIPbar.setTextVisible(True)
        self.VVIPbar.setObjectName("VVIPbar")
        self.DailyOccupancyLabel = QtWidgets.QLabel(self.centralwidget)
        self.DailyOccupancyLabel.setGeometry(QtCore.QRect(458, 296, 153, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DailyOccupancyLabel.setFont(font)
        self.DailyOccupancyLabel.setObjectName("DailyOccupancyLabel")
        self.OverviewSummaryLabel = QtWidgets.QLabel(self.centralwidget)
        self.OverviewSummaryLabel.setGeometry(QtCore.QRect(464, 66, 351, 41))
        self.OverviewSummaryLabel.setFont(font)
        self.OverviewSummaryLabel.setStyleSheet("")
        self.OverviewSummaryLabel.setObjectName("OverviewSummaryLabel")
        self.SiteLabel = QtWidgets.QLabel(self.centralwidget)
        self.SiteLabel.setGeometry(QtCore.QRect(32, 122, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SiteLabel.setFont(font)
        self.SiteLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.SiteLabel.setObjectName("SiteLabel")
        self.VisitorsOverviewbar = QtWidgets.QProgressBar(self.centralwidget)
        self.VisitorsOverviewbar.setGeometry(QtCore.QRect(466, 204, 290, 10))
        self.VisitorsOverviewbar.setStyleSheet(open("./qss/0_to_99%.qss", "r").read())
        self.VisitorsOverviewbar.setProperty("value", 0)
        self.VisitorsOverviewbar.setTextVisible(True)
        self.VisitorsOverviewbar.setObjectName("VisitorsOverviewbar")
        self.VisitorsOverviewLabel = QtWidgets.QLabel(self.centralwidget)
        self.VisitorsOverviewLabel.setGeometry(QtCore.QRect(466, 178, 57, 16))
        self.VisitorsOverviewLabel.setFont(font)
        self.VisitorsOverviewLabel.setObjectName("VisitorsOverviewLabel")
        self.OccupancyLabelbar = QtWidgets.QProgressBar(self.centralwidget)
        self.OccupancyLabelbar.setGeometry(QtCore.QRect(466, 258, 290, 10))
        self.OccupancyLabelbar.setStyleSheet(open("./qss/0_to_99%.qss", "r").read())
        self.OccupancyLabelbar.setProperty("value", 0)
        self.OccupancyLabelbar.setTextVisible(True)
        self.OccupancyLabelbar.setObjectName("OccupancyLabelbar")
        self.OccupancyLabel = QtWidgets.QLabel(self.centralwidget)
        self.OccupancyLabel.setGeometry(QtCore.QRect(466, 234, 85, 16))
        self.OccupancyLabel.setFont(font)
        self.OccupancyLabel.setObjectName("OccupancyLabel")
        self.OpeningHoursLabel = QtWidgets.QLabel(self.centralwidget)
        self.OpeningHoursLabel.setGeometry(QtCore.QRect(26, 558, 109, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OpeningHoursLabel.setFont(font)
        self.OpeningHoursLabel.setObjectName("OpeningHoursLabel")
        self.icon = QtWidgets.QLabel(self.centralwidget)
        self.icon.setGeometry(QtCore.QRect(34, 36, 61, 55))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.icon.setFont(font)
        self.icon.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("icon/car.png"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.SPSlabel = QtWidgets.QLabel(self.centralwidget)
        self.SPSlabel.setGeometry(QtCore.QRect(670, 762, 313, 23))
        self.SPSlabel.setObjectName("SPSlabel")
        self.ParkingNavigation = QtWidgets.QComboBox(self.centralwidget)
        self.ParkingNavigation.setGeometry(QtCore.QRect(124, 60, 133, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ParkingNavigation.setFont(font)
        self.ParkingNavigation.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.ParkingNavigation.setEditable(False)
        self.ParkingNavigation.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.ParkingNavigation.setFrame(False)
        self.ParkingNavigation.setObjectName("ParkingNavigation")
        self.ParkingNavigation.addItem("")
        self.VVIPText = QtWidgets.QLabel(self.centralwidget)
        self.VVIPText.setGeometry(QtCore.QRect(40, 196, 113, 29))
        self.VVIPText.setFont(font)
        self.VVIPText.setObjectName("VVIPText")
        self.SpecialNeedText = QtWidgets.QLabel(self.centralwidget)
        self.SpecialNeedText.setGeometry(QtCore.QRect(40, 272, 137, 29))
        self.SpecialNeedText.setFont(font)
        self.SpecialNeedText.setObjectName("SpecialNeedText")
        self.ZoneAText = QtWidgets.QLabel(self.centralwidget)
        self.ZoneAText.setGeometry(QtCore.QRect(40, 340, 71, 27))
        self.ZoneAText.setFont(font)
        self.ZoneAText.setObjectName("ZoneAText")
        self.ZoneBText = QtWidgets.QLabel(self.centralwidget)
        self.ZoneBText.setGeometry(QtCore.QRect(40, 410, 71, 25))
        self.ZoneBText.setFont(font)
        self.ZoneBText.setObjectName("ZoneBText")
        self.VisitorsText = QtWidgets.QLabel(self.centralwidget)
        self.VisitorsText.setGeometry(QtCore.QRect(40, 480, 81, 25))
        self.VisitorsText.setFont(font)
        self.VisitorsText.setObjectName("VisitorsText")
        self.VVIPPercentageOccupied = QtWidgets.QLabel(self.centralwidget)
        self.VVIPPercentageOccupied.setGeometry(QtCore.QRect(28, 222, 93, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.VVIPPercentageOccupied.setFont(font)
        self.VVIPPercentageOccupied.setObjectName("VVIPPercentageOccupied")
        self.VVIPSpaceLeft = QtWidgets.QLabel(self.centralwidget)
        self.VVIPSpaceLeft.setGeometry(QtCore.QRect(262, 224, 47, 16))
        self.VVIPSpaceLeft.setFont(font)
        self.VVIPSpaceLeft.setObjectName("VVIPSpaceLeft")
        self.SpecialNeedSpaceLeft = QtWidgets.QLabel(self.centralwidget)
        self.SpecialNeedSpaceLeft.setGeometry(QtCore.QRect(262, 302, 47, 16))
        self.SpecialNeedSpaceLeft.setFont(font)
        self.SpecialNeedSpaceLeft.setObjectName("SpecialNeedSpaceLeft")
        self.SpecialNeedPercentageOccupied = QtWidgets.QLabel(self.centralwidget)
        self.SpecialNeedPercentageOccupied.setGeometry(QtCore.QRect(28, 300, 93, 20))
        self.SpecialNeedPercentageOccupied.setFont(font)
        self.SpecialNeedPercentageOccupied.setObjectName("SpecialNeedPercentageOccupied")
        self.ZoneASpaceLeft = QtWidgets.QLabel(self.centralwidget)
        self.ZoneASpaceLeft.setGeometry(QtCore.QRect(262, 370, 47, 16))
        self.ZoneASpaceLeft.setFont(font)
        self.ZoneASpaceLeft.setObjectName("ZoneASpaceLeft")
        self.ZoneAPercentageOccupied = QtWidgets.QLabel(self.centralwidget)
        self.ZoneAPercentageOccupied.setGeometry(QtCore.QRect(28, 368, 93, 20))
        self.ZoneAPercentageOccupied.setFont(font)
        self.ZoneAPercentageOccupied.setObjectName("ZoneAPercentageOccupied")
        self.ZoneBSpaceLeft = QtWidgets.QLabel(self.centralwidget)
        self.ZoneBSpaceLeft.setGeometry(QtCore.QRect(262, 436, 47, 16))
        self.ZoneBSpaceLeft.setFont(font)
        self.ZoneBSpaceLeft.setObjectName("ZoneBSpaceLeft")
        self.ZoneBPercentageOccupied = QtWidgets.QLabel(self.centralwidget)
        self.ZoneBPercentageOccupied.setGeometry(QtCore.QRect(28, 434, 93, 20))
        self.ZoneBPercentageOccupied.setFont(font)
        self.ZoneBPercentageOccupied.setObjectName("ZoneBPercentageOccupied")
        self.VisitorsSpaceLeft = QtWidgets.QLabel(self.centralwidget)
        self.VisitorsSpaceLeft.setGeometry(QtCore.QRect(262, 506, 47, 16))
        self.VisitorsSpaceLeft.setFont(font)
        self.VisitorsSpaceLeft.setObjectName("VisitorsSpaceLeft")
        self.VisitorsPercentageOccupied = QtWidgets.QLabel(self.centralwidget)
        self.VisitorsPercentageOccupied.setGeometry(QtCore.QRect(28, 504, 93, 20))
        self.VisitorsPercentageOccupied.setFont(font)
        self.VisitorsPercentageOccupied.setObjectName("VisitorsPercentageOccupied")
        self.VVIParrow = QtWidgets.QLabel(self.centralwidget)
        self.VVIParrow.setGeometry(QtCore.QRect(294, 204, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.VVIParrow.setFont(font)
        self.VVIParrow.setText("")
        self.VVIParrow.setPixmap(QtGui.QPixmap("icon/arrow2.png"))
        self.VVIParrow.setScaledContents(True)
        self.VVIParrow.setObjectName("VVIParrow")
        self.SpecialNeedarrow = QtWidgets.QLabel(self.centralwidget)
        self.SpecialNeedarrow.setGeometry(QtCore.QRect(294, 282, 16, 16))
        self.SpecialNeedarrow.setFont(font)
        self.SpecialNeedarrow.setText("")
        self.SpecialNeedarrow.setPixmap(QtGui.QPixmap("icon/arrow2.png"))
        self.SpecialNeedarrow.setScaledContents(True)
        self.SpecialNeedarrow.setObjectName("SpecialNeedarrow")
        self.ZoneAarrow = QtWidgets.QLabel(self.centralwidget)
        self.ZoneAarrow.setGeometry(QtCore.QRect(294, 352, 16, 16))
        self.ZoneAarrow.setFont(font)
        self.ZoneAarrow.setText("")
        self.ZoneAarrow.setPixmap(QtGui.QPixmap("icon/arrow2.png"))
        self.ZoneAarrow.setScaledContents(True)
        self.ZoneAarrow.setObjectName("ZoneAarrow")
        self.ZoneBarrow = QtWidgets.QLabel(self.centralwidget)
        self.ZoneBarrow.setGeometry(QtCore.QRect(294, 418, 16, 16))
        self.ZoneBarrow.setFont(font)
        self.ZoneBarrow.setText("")
        self.ZoneBarrow.setPixmap(QtGui.QPixmap("icon/arrow2.png"))
        self.ZoneBarrow.setScaledContents(True)
        self.ZoneBarrow.setObjectName("ZoneBarrow")
        self.Visitorsarrow = QtWidgets.QLabel(self.centralwidget)
        self.Visitorsarrow.setGeometry(QtCore.QRect(294, 484, 16, 16))
        self.Visitorsarrow.setFont(font)
        self.Visitorsarrow.setText("")
        self.Visitorsarrow.setPixmap(QtGui.QPixmap("icon/arrow2.png"))
        self.Visitorsarrow.setScaledContents(True)
        self.Visitorsarrow.setObjectName("Visitorsarrow")
        self.SpecialNeedbar = QtWidgets.QProgressBar(self.centralwidget)
        self.SpecialNeedbar.setGeometry(QtCore.QRect(30, 322, 280, 10))
        self.SpecialNeedbar.setStyleSheet(open("./qss/0_to_99%.qss", "r").read())
        self.SpecialNeedbar.setProperty("value", 0)
        self.SpecialNeedbar.setTextVisible(True)
        self.SpecialNeedbar.setObjectName("SpecialNeedbar")
        self.ZoneAbar = QtWidgets.QProgressBar(self.centralwidget)
        self.ZoneAbar.setGeometry(QtCore.QRect(30, 392, 280, 10))
        self.ZoneAbar.setStyleSheet(open("./qss/0_to_99%.qss", "r").read())
        self.ZoneAbar.setProperty("value", 0)
        self.ZoneAbar.setTextVisible(True)
        self.ZoneAbar.setObjectName("ZoneAbar")
        self.ZoneBbar = QtWidgets.QProgressBar(self.centralwidget)
        self.ZoneBbar.setGeometry(QtCore.QRect(30, 460, 280, 10))
        self.ZoneBbar.setStyleSheet(open("./qss/0_to_99%.qss", "r").read())
        self.ZoneBbar.setProperty("value", 0)
        self.ZoneBbar.setTextVisible(True)
        self.ZoneBbar.setObjectName("ZoneBbar")
        self.Visitorsbar = QtWidgets.QProgressBar(self.centralwidget)
        self.Visitorsbar.setGeometry(QtCore.QRect(30, 530, 280, 10))
        self.Visitorsbar.setStyleSheet(open("./qss/0_to_99%.qss", "r").read())
        self.Visitorsbar.setProperty("value", 0)
        self.Visitorsbar.setTextVisible(True)
        self.Visitorsbar.setObjectName("Visitorsbar")
        self.VVIPLabel = QtWidgets.QLabel(self.centralwidget)
        self.VVIPLabel.setGeometry(QtCore.QRect(20, 190, 300, 70))
        self.VVIPLabel.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.VVIPLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VVIPLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.VVIPLabel.setText("")
        self.VVIPLabel.setObjectName("VVIPLabel")
        self.SpecialNeedLabel = QtWidgets.QLabel(self.centralwidget)
        self.SpecialNeedLabel.setGeometry(QtCore.QRect(20, 270, 300, 70))
        self.SpecialNeedLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SpecialNeedLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.SpecialNeedLabel.setText("")
        self.SpecialNeedLabel.setObjectName("SpecialNeedLabel")
        self.ZoneALabel = QtWidgets.QLabel(self.centralwidget)
        self.ZoneALabel.setGeometry(QtCore.QRect(20, 338, 300, 70))
        self.ZoneALabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ZoneALabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ZoneALabel.setText("")
        self.ZoneALabel.setObjectName("ZoneALabel")
        self.VisitorsLabel = QtWidgets.QLabel(self.centralwidget)
        self.VisitorsLabel.setGeometry(QtCore.QRect(20, 474, 300, 73))
        self.VisitorsLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VisitorsLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.VisitorsLabel.setText("")
        self.VisitorsLabel.setObjectName("VisitorsLabel")
        self.ZoneBLabel = QtWidgets.QLabel(self.centralwidget)
        self.ZoneBLabel.setGeometry(QtCore.QRect(20, 406, 300, 70))
        self.ZoneBLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ZoneBLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ZoneBLabel.setText("")
        self.ZoneBLabel.setObjectName("ZoneBLabel")
        self.VVIPOpenIcon = QtWidgets.QLabel(self.centralwidget)
        self.VVIPOpenIcon.setGeometry(QtCore.QRect(235, 204, 50, 16))
        self.VVIPOpenIcon.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.VVIPOpenIcon.setText("")
        self.VVIPOpenIcon.setPixmap(QtGui.QPixmap("icon/open.png"))
        self.VVIPOpenIcon.setScaledContents(True)
        self.VVIPOpenIcon.setObjectName("VVIPOpenIcon")
        self.SpecialNeedOpenIcon = QtWidgets.QLabel(self.centralwidget)
        self.SpecialNeedOpenIcon.setGeometry(QtCore.QRect(235, 282, 50, 16))
        self.SpecialNeedOpenIcon.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SpecialNeedOpenIcon.setText("")
        self.SpecialNeedOpenIcon.setPixmap(QtGui.QPixmap("icon/open.png"))
        self.SpecialNeedOpenIcon.setScaledContents(True)
        self.SpecialNeedOpenIcon.setObjectName("SpecialNeedOpenIcon")
        self.ZoneAOpenIcon = QtWidgets.QLabel(self.centralwidget)
        self.ZoneAOpenIcon.setGeometry(QtCore.QRect(235, 350, 50, 16))
        self.ZoneAOpenIcon.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ZoneAOpenIcon.setText("")
        self.ZoneAOpenIcon.setPixmap(QtGui.QPixmap("icon/open.png"))
        self.ZoneAOpenIcon.setScaledContents(True)
        self.ZoneAOpenIcon.setObjectName("ZoneAOpenIcon")
        self.ZoneBOpenIcon = QtWidgets.QLabel(self.centralwidget)
        self.ZoneBOpenIcon.setGeometry(QtCore.QRect(235, 418, 50, 16))
        self.ZoneBOpenIcon.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ZoneBOpenIcon.setText("")
        self.ZoneBOpenIcon.setPixmap(QtGui.QPixmap("icon/open.png"))
        self.ZoneBOpenIcon.setScaledContents(True)
        self.ZoneBOpenIcon.setObjectName("ZoneBOpenIcon")
        self.VisitorsOpenIcon = QtWidgets.QLabel(self.centralwidget)
        self.VisitorsOpenIcon.setGeometry(QtCore.QRect(235, 484, 50, 16))
        self.VisitorsOpenIcon.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.VisitorsOpenIcon.setText("")
        self.VisitorsOpenIcon.setPixmap(QtGui.QPixmap("icon/open.png"))
        self.VisitorsOpenIcon.setScaledContents(True)
        self.VisitorsOpenIcon.setObjectName("VisitorsOpenIcon")
        self.graphicsView = pg.PlotWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(458, 324, 800, 430))
        self.graphicsView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.graphicsView.setFrameShape(QtWidgets.QFrame.Box)
        self.graphicsView.setObjectName("graphicsView")
        self.allGraph = QtWidgets.QPushButton(self.centralwidget)
        self.allGraph.setGeometry(QtCore.QRect(304, 680, 75, 70))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.allGraph.setFont(font)
        self.allGraph.setStyleSheet("")
        self.allGraph.setObjectName("pushButton")
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.CapacityText = QtWidgets.QLabel(self.centralwidget)
        self.CapacityText.setGeometry(QtCore.QRect(467, 138, 47, 28))
        self.CapacityText.setFont(font)
        self.CapacityText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CapacityText.setAlignment(QtCore.Qt.AlignCenter)
        self.CapacityText.setWordWrap(False)
        self.CapacityText.setObjectName("CapacityText")
        self.TypeText = QtWidgets.QLabel(self.centralwidget)
        self.TypeText.setGeometry(QtCore.QRect(567, 138, 87, 26))
        self.TypeText.setFont(font)
        self.TypeText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TypeText.setAlignment(QtCore.Qt.AlignCenter)
        self.TypeText.setObjectName("TypeText")
        self.TimeZoneText = QtWidgets.QLabel(self.centralwidget)
        self.TimeZoneText.setGeometry(QtCore.QRect(690, 138, 97, 26))
        self.TimeZoneText.setFont(font)
        self.TimeZoneText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TimeZoneText.setAlignment(QtCore.Qt.AlignCenter)
        self.TimeZoneText.setObjectName("TimeZoneText")
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.TueBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.TueBtn.setGeometry(QtCore.QRect(30, 612, 23, 20))
        self.TueBtn.setText("")
        self.TueBtn.setObjectName("TueBtn")
        self.MonBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.MonBtn.setGeometry(QtCore.QRect(30, 588, 25, 20))
        self.MonBtn.setText("")
        self.MonBtn.setObjectName("MonBtn")
        self.WedBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.WedBtn.setGeometry(QtCore.QRect(30, 636, 23, 20))
        self.WedBtn.setText("")
        self.WedBtn.setObjectName("WedBtn")
        self.ThursBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.ThursBtn.setGeometry(QtCore.QRect(30, 660, 23, 20))
        self.ThursBtn.setText("")
        self.ThursBtn.setObjectName("ThursBtn")
        self.FriBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.FriBtn.setGeometry(QtCore.QRect(30, 684, 21, 20))
        self.FriBtn.setText("")
        self.FriBtn.setObjectName("FriBtn")
        self.SatBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.SatBtn.setGeometry(QtCore.QRect(30, 708, 23, 20))
        self.SatBtn.setText("")
        self.SatBtn.setObjectName("SatBtn")
        self.SunBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.SunBtn.setGeometry(QtCore.QRect(30, 732, 25, 20))
        self.SunBtn.setText("")
        self.SunBtn.setObjectName("SunBtn")
        self.Mon = QtWidgets.QLabel(self.centralwidget)
        self.Mon.setGeometry(QtCore.QRect(59, 585, 57, 20))
        self.Mon.setFont(font)
        self.Mon.setStyleSheet("")
        self.Mon.setObjectName("Mon")
        self.Tue = QtWidgets.QLabel(self.centralwidget)
        self.Tue.setGeometry(QtCore.QRect(59, 609, 63, 20))
        self.Tue.setFont(font)
        self.Tue.setObjectName("Tue")
        self.Wed = QtWidgets.QLabel(self.centralwidget)
        self.Wed.setGeometry(QtCore.QRect(59, 634, 75, 20))
        self.Wed.setFont(font)
        self.Wed.setStyleSheet("")
        self.Wed.setObjectName("Wed")
        self.Thurs = QtWidgets.QLabel(self.centralwidget)
        self.Thurs.setGeometry(QtCore.QRect(59, 658, 57, 20))
        self.Thurs.setFont(font)
        self.Thurs.setObjectName("Thurs")
        self.Fri = QtWidgets.QLabel(self.centralwidget)
        self.Fri.setGeometry(QtCore.QRect(59, 683, 45, 20))
        self.Fri.setFont(font)
        self.Fri.setObjectName("Fri")
        self.Sat = QtWidgets.QLabel(self.centralwidget)
        self.Sat.setGeometry(QtCore.QRect(59, 707, 57, 20))
        self.Sat.setFont(font)
        self.Sat.setObjectName("Sat")
        self.Sun = QtWidgets.QLabel(self.centralwidget)
        self.Sun.setGeometry(QtCore.QRect(59, 732, 51, 20))
        self.Sun.setFont(font)
        self.Sun.setObjectName("Sun")
        self.FriTime = QtWidgets.QLabel(self.centralwidget)
        self.FriTime.setGeometry(QtCore.QRect(175, 683, 59, 20))
        self.FriTime.setFont(font)
        self.FriTime.setObjectName("FriTime")
        self.MonTime = QtWidgets.QLabel(self.centralwidget)
        self.MonTime.setGeometry(QtCore.QRect(175, 585, 85, 20))
        self.MonTime.setFont(font)
        self.MonTime.setObjectName("MonTime")
        self.TueTime = QtWidgets.QLabel(self.centralwidget)
        self.TueTime.setGeometry(QtCore.QRect(175, 609, 63, 20))
        self.TueTime.setFont(font)
        self.TueTime.setObjectName("TueTime")
        self.WedTime = QtWidgets.QLabel(self.centralwidget)
        self.WedTime.setGeometry(QtCore.QRect(175, 634, 63, 20))
        self.WedTime.setFont(font)
        self.WedTime.setObjectName("WedTime")
        self.ThursTime = QtWidgets.QLabel(self.centralwidget)
        self.ThursTime.setGeometry(QtCore.QRect(175, 658, 61, 20))
        self.ThursTime.setFont(font)
        self.ThursTime.setObjectName("ThursTime")
        self.SatTime = QtWidgets.QLabel(self.centralwidget)
        self.SatTime.setGeometry(QtCore.QRect(175, 707, 83, 20))
        self.SatTime.setFont(font)
        self.SatTime.setObjectName("SatTime")
        self.SunTime = QtWidgets.QLabel(self.centralwidget)
        self.SunTime.setGeometry(QtCore.QRect(175, 732, 81, 20))
        self.SunTime.setFont(font)
        self.SunTime.setObjectName("SunTime")

        self.CapacityLabel = QtWidgets.QLabel(self.centralwidget)
        self.CapacityLabel.setGeometry(QtCore.QRect(468, 112, 53, 20))
        self.CapacityLabel.setFont(font)
        self.CapacityLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CapacityLabel.setObjectName("CapacityLabel")
        self.TypeLabel = QtWidgets.QLabel(self.centralwidget)
        self.TypeLabel.setGeometry(QtCore.QRect(588, 112, 29, 20))
        self.TypeLabel.setFont(font)
        self.TypeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TypeLabel.setObjectName("TypeLabel")
        self.TimeZoneLabel = QtWidgets.QLabel(self.centralwidget)
        self.TimeZoneLabel.setGeometry(QtCore.QRect(698, 112, 69, 20))
        self.TimeZoneLabel.setFont(font)
        self.TimeZoneLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TimeZoneLabel.setObjectName("TimeZoneLabel")
        self.menuBar = QtWidgets.QMenuBar()
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        Overview.setMenuBar(self.menuBar)
        self.actionBrowse = QtWidgets.QAction(Overview)
        self.actionBrowse.setObjectName("actionBrowse")
        self.actionSave = QtWidgets.QAction(Overview)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(Overview)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionBrowse)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.VVIPLabel.raise_()
        self.SpecialNeedLabel.raise_()
        self.ZoneALabel.raise_()
        self.ZoneBLabel.raise_()
        self.VisitorsLabel.raise_()
        self.SiteCombox.raise_()
        self.VVIPbar.raise_()
        self.DailyOccupancyLabel.raise_()
        self.OverviewSummaryLabel.raise_()
        self.SiteLabel.raise_()
        self.VisitorsOverviewbar.raise_()
        self.VisitorsOverviewLabel.raise_()
        self.OccupancyLabelbar.raise_()
        self.OccupancyLabel.raise_()
        self.OpeningHoursLabel.raise_()
        self.SPSlabel.raise_()
        self.ParkingNavigation.raise_()
        self.VVIPText.raise_()
        self.SpecialNeedText.raise_()
        self.ZoneAText.raise_()
        self.ZoneBText.raise_()
        self.VisitorsText.raise_()
        self.VVIPPercentageOccupied.raise_()
        self.VVIPSpaceLeft.raise_()
        self.SpecialNeedSpaceLeft.raise_()
        self.SpecialNeedPercentageOccupied.raise_()
        self.ZoneASpaceLeft.raise_()
        self.ZoneAPercentageOccupied.raise_()
        self.ZoneBSpaceLeft.raise_()
        self.ZoneBPercentageOccupied.raise_()
        self.VisitorsSpaceLeft.raise_()
        self.VisitorsPercentageOccupied.raise_()
        self.VVIParrow.raise_()
        self.SpecialNeedarrow.raise_()
        self.ZoneAarrow.raise_()
        self.ZoneBarrow.raise_()
        self.Visitorsarrow.raise_()
        self.SpecialNeedbar.raise_()
        self.ZoneAbar.raise_()
        self.ZoneBbar.raise_()
        self.Visitorsbar.raise_()
        self.icon.raise_()
        self.VVIPOpenIcon.raise_()
        self.SpecialNeedOpenIcon.raise_()
        self.ZoneAOpenIcon.raise_()
        self.ZoneBOpenIcon.raise_()
        self.VisitorsOpenIcon.raise_()
        self.graphicsView.raise_()
        self.allGraph.raise_()
        Overview.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Overview)
        self.statusbar.setObjectName("statusbar")
        Overview.setStatusBar(self.statusbar)

        self.retranslateUi(Overview)
        QtCore.QMetaObject.connectSlotsByName(Overview)

        self.graphicsView.showGrid(x=True, y=True)
        self.graphicsView.setLabel('left', 'Number of visitors')
        self.graphicsView.setLabel('bottom', 'Hours')
        self.graphicsView.setStyleSheet(qdarkstyle.load_stylesheet(qt_api=os.environ['PYQTGRAPH_QT_LIB']))
        self.MonBtn.clicked.connect(self.button_state)
        self.TueBtn.clicked.connect(self.button_state)
        self.WedBtn.clicked.connect(self.button_state)
        self.ThursBtn.clicked.connect(self.button_state)
        self.FriBtn.clicked.connect(self.button_state)
        self.SatBtn.clicked.connect(self.button_state)
        self.SunBtn.clicked.connect(self.button_state)

        self.allGraph.clicked.connect(self.bar_graph)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "overview"))
        self.SiteCombox.setItemText(0, _translate("MainWindow", "New Item"))
        self.SiteCombox.setStatusTip(_translate("MainWindow", "Site Combo"))
        self.DailyOccupancyLabel.setText(_translate("MainWindow", "Daily Occupancy"))
        self.DailyOccupancyLabel.setStatusTip(_translate("MainWindow", "Daily Occupancy"))
        self.OverviewSummaryLabel.setText(_translate("MainWindow", "FLEX Plant 5 Car Park : Overview Summary"))
        self.OverviewSummaryLabel.setStatusTip(_translate("MainWindow", "Overview Summary Label"))
        self.SiteLabel.setText(_translate("MainWindow", "Site"))
        self.SiteLabel.setStatusTip(_translate("MainWindow", "Site Label"))
        self.VisitorsOverviewLabel.setText(_translate("MainWindow", "Visitors"))
        self.VisitorsOverviewLabel.setStatusTip(_translate("MainWindow", "Visitors Overview Label"))
        self.OccupancyLabel.setText(_translate("MainWindow", "Occupancy"))
        self.OccupancyLabel.setStatusTip(_translate("MainWindow", "Occupancy Label"))
        self.OpeningHoursLabel.setText(_translate("MainWindow", "Opening hours"))
        self.OpeningHoursLabel.setStatusTip(_translate("MainWindow", "Opening Hours Label"))
        self.SPSlabel.setText(_translate("MainWindow", "SPS® Project is collaborative work between FLEX and UniMAP"))
        self.SPSlabel.setStatusTip(_translate("MainWindow", "SPS label"))
        self.ParkingNavigation.setItemText(0, _translate("MainWindow", "Parking"))
        self.ParkingNavigation.setStatusTip(_translate("MainWindow", "Parking Navigation"))
        self.VVIPText.setText(_translate("MainWindow", "VVIP Space"))
        self.VVIPText.setStatusTip(_translate("MainWindow", "VVIP Space"))
        self.SpecialNeedText.setText(_translate("MainWindow", "Special Need"))
        self.SpecialNeedText.setStatusTip(_translate("MainWindow", "Special Need"))
        self.ZoneAText.setText(_translate("MainWindow", "Zone A"))
        self.ZoneAText.setStatusTip(_translate("MainWindow", "Zone A"))
        self.ZoneBText.setText(_translate("MainWindow", "Zone B"))
        self.ZoneBText.setStatusTip(_translate("MainWindow", "Zone B"))
        self.VisitorsText.setText(_translate("MainWindow", "Visitors"))
        self.VisitorsText.setStatusTip(_translate("MainWindow", "Visitors"))
        self.VVIPPercentageOccupied.setText(_translate("MainWindow", "0% occupied"))
        self.VVIPPercentageOccupied.setStatusTip(_translate("MainWindow", "VVIP Percentage Occupied"))
        self.VVIPSpaceLeft.setText(_translate("MainWindow", "0 free"))
        self.VVIPSpaceLeft.setStatusTip(_translate("MainWindow", "VVIP Space Left"))
        self.SpecialNeedSpaceLeft.setText(_translate("MainWindow", "0 free"))
        self.SpecialNeedSpaceLeft.setStatusTip(_translate("MainWindow", "Special Need Space Left"))
        self.SpecialNeedPercentageOccupied.setText(_translate("MainWindow", "0% occupied"))
        self.SpecialNeedPercentageOccupied.setStatusTip(_translate("MainWindow", "Special Need Percentage Occupied"))
        self.ZoneASpaceLeft.setText(_translate("MainWindow", "0 free"))
        self.ZoneASpaceLeft.setStatusTip(_translate("MainWindow", "Zone A Space Left"))
        self.ZoneAPercentageOccupied.setText(_translate("MainWindow", "0% occupied"))
        self.ZoneAPercentageOccupied.setStatusTip(_translate("MainWindow", "Zone A Percentage Occupied"))
        self.ZoneBSpaceLeft.setText(_translate("MainWindow", "0 free"))
        self.ZoneBSpaceLeft.setStatusTip(_translate("MainWindow", "Zone B Space Left"))
        self.ZoneBPercentageOccupied.setText(_translate("MainWindow", "0% occupied"))
        self.ZoneBPercentageOccupied.setStatusTip(_translate("MainWindow", "Zone B Percentage Occupied"))
        self.VisitorsSpaceLeft.setText(_translate("MainWindow", "0 free"))
        self.VisitorsSpaceLeft.setStatusTip(_translate("MainWindow", "Visitors Space Left"))
        self.VisitorsPercentageOccupied.setText(_translate("MainWindow", "0% occupied"))
        self.VisitorsPercentageOccupied.setStatusTip(_translate("MainWindow", "Visitors Percentage Occupied"))
        self.allGraph.setText(_translate("MainWindow", "All"))
        self.allGraph.setStatusTip(_translate("MainWindow", "All Graph"))
        self.Mon.setText(_translate("MainWindow", "Monday"))
        self.Mon.setStatusTip(_translate("MainWindow", "Monday"))
        self.Tue.setText(_translate("MainWindow", "Tuesday"))
        self.Tue.setStatusTip(_translate("MainWindow", "Tuesday"))
        self.Wed.setText(_translate("MainWindow", "Wednesday"))
        self.Wed.setStatusTip(_translate("MainWindow", "Wednesday"))
        self.Thurs.setText(_translate("MainWindow", "Thursday"))
        self.Thurs.setStatusTip(_translate("MainWindow", "Thursday"))
        self.Fri.setText(_translate("MainWindow", "Friday"))
        self.Fri.setStatusTip(_translate("MainWindow", "Friday"))
        self.Sat.setText(_translate("MainWindow", "Saturday"))
        self.Sat.setStatusTip(_translate("MainWindow", "Saturday"))
        self.Sun.setText(_translate("MainWindow", "Sunday"))
        self.Sun.setStatusTip(_translate("MainWindow", "Sunday"))
        self.FriTime.setText(_translate("MainWindow", "24 Hours"))
        self.FriTime.setStatusTip(_translate("MainWindow", "Friday Time"))
        self.MonTime.setText(_translate("MainWindow", "07:00 - 00:00"))
        self.MonTime.setStatusTip(_translate("MainWindow", "Monday Time"))
        self.TueTime.setText(_translate("MainWindow", "24 Hours"))
        self.TueTime.setStatusTip(_translate("MainWindow", "Tuesday Time"))
        self.WedTime.setText(_translate("MainWindow", "24 Hours"))
        self.WedTime.setStatusTip(_translate("MainWindow", "Wednesday Time"))
        self.ThursTime.setText(_translate("MainWindow", "24 Hours"))
        self.ThursTime.setStatusTip(_translate("MainWindow", "Thursday Time"))
        self.SatTime.setText(_translate("MainWindow", "00.00 - 22.00"))
        self.SatTime.setStatusTip(_translate("MainWindow", "Saturday Time"))
        self.SunTime.setText(_translate("MainWindow", "10.00 - 18.00"))
        self.SunTime.setStatusTip(_translate("MainWindow", "Sunday Time"))
        self.CapacityText.setText(_translate("MainWindow", "209"))
        self.CapacityText.setStatusTip(_translate("MainWindow", "Capacity"))
        self.TypeText.setText(_translate("MainWindow", "Car Park"))
        self.TypeText.setStatusTip(_translate("MainWindow", "Car Park"))
        self.TimeZoneText.setText(_translate("MainWindow", "Malaysia"))
        self.TimeZoneText.setStatusTip(_translate("MainWindow", "Time Zone"))
        self.CapacityLabel.setText(_translate("MainWindow", "Capacity"))
        self.CapacityLabel.setStatusTip(_translate("MainWindow", "Capacity"))
        self.TypeLabel.setText(_translate("MainWindow", "Type"))
        self.TypeLabel.setStatusTip(_translate("MainWindow", "Type"))
        self.TimeZoneLabel.setText(_translate("MainWindow", "Time zone"))
        self.TimeZoneLabel.setStatusTip(_translate("MainWindow", "Time zone"))
        self.VVIPbar.setStatusTip(_translate("MainWindow", "VVIP bar"))
        self.SpecialNeedbar.setStatusTip(_translate("MainWindow", "Special Need bar"))
        self.ZoneAbar.setStatusTip(_translate("MainWindow", "Zone A bar"))
        self.ZoneBbar.setStatusTip(_translate("MainWindow", "Zone B bar"))
        self.Visitorsbar.setStatusTip(_translate("MainWindow", "Visitors bar"))
        self.graphicsView.setStatusTip(_translate("MainWindow", "Graph"))
        self.icon.setStatusTip(_translate("MainWindow", "Icon"))
        self.menuFile.setTitle(_translate("video", "File"))
        self.actionBrowse.setText(_translate("video", "Browse"))
        self.actionBrowse.setShortcut(_translate("video", "Ctrl+N"))
        self.actionBrowse.setStatusTip(_translate("video", "Browse"))
        self.actionSave.setText(_translate("video", "Save"))
        self.actionSave.setShortcut(_translate("video", "Ctrl+S"))
        self.actionSave.setStatusTip(_translate("video", "Save"))
        self.actionExit.setText(_translate("video", "Exit"))
        self.actionExit.setShortcut(_translate("video", "Ctrl+E"))
        self.actionExit.setStatusTip(_translate("video", "Exit"))

    def button_state(self):
        data = pd.read_csv('test.csv')
        self.x = data.hour

        if self.MonBtn.isChecked():
            self.graphicsView.clear()
            self.y = data.Mon
            pen = pg.mkPen(color="#FFFFFF")
            self.graphicsView.plot(self.x, self.y, pen=pen)

        elif self.TueBtn.isChecked():
            self.graphicsView.clear()
            self.y = data.Tue
            pen = pg.mkPen(color="#FF0000")
            self.graphicsView.plot(self.x, self.y, pen=pen)

        elif self.WedBtn.isChecked():
            self.graphicsView.clear()
            self.y = data.Wed
            pen = pg.mkPen(color="#0000FF")
            self.graphicsView.plot(self.x, self.y, pen=pen)

        elif self.ThursBtn.isChecked():
            self.graphicsView.clear()
            self.y = data.Thurs
            pen = pg.mkPen(color="#00FFFF")
            self.graphicsView.plot(self.x, self.y, pen=pen)

        elif self.FriBtn.isChecked():
            self.graphicsView.clear()
            self.y = data.Fri
            pen = pg.mkPen(color="#00FF00")
            self.graphicsView.plot(self.x, self.y, pen=pen)

        elif self.SatBtn.isChecked():
            self.graphicsView.clear()
            self.y = data.Sat
            pen = pg.mkPen(color="#FFA500")
            self.graphicsView.plot(self.x, self.y, pen=pen)

        elif self.SunBtn.isChecked():
            self.graphicsView.clear()
            self.y = data.Sun
            pen = pg.mkPen(color="#800080")
            self.graphicsView.plot(self.x, self.y, pen=pen)

    def bar_graph(self):
        self.graphicsView.clear()
        data = pd.read_csv('test.csv')
        self.x = data.Day
        self.y = data.Average
        self.xdict = dict(enumerate(self.x))

        bg = pg.BarGraphItem(x=list(self.xdict.keys()), height=self.y, width=0.3, brush='r')

        self.graphicsView.addItem(bg)

    def all_plot(self):
        self.graphicsView.clear()
        data = pd.read_csv('test.csv')

        self.x = data.hour
        self.y = data.Mon
        self.y2 = data.Tue
        self.y3 = data.Wed
        self.y4 = data.Thurs
        self.y5 = data.Fri
        self.y6 = data.Sat
        self.y7 = data.Sun

        pen = pg.mkPen(color="#000000")
        pen2 = pg.mkPen(color="#FF0000")
        pen3 = pg.mkPen(color="#0000FF")
        pen4 = pg.mkPen(color="#00FFFF")
        pen5 = pg.mkPen(color="#00FF00")
        pen6 = pg.mkPen(color="#FFA500")
        pen7 = pg.mkPen(color="#800080")

        self.graphicsView.plot(self.x, self.y, pen=pen)
        self.graphicsView.plot(self.x, self.y2, pen=pen2)
        self.graphicsView.plot(self.x, self.y3, pen=pen3)
        self.graphicsView.plot(self.x, self.y4, pen=pen4)
        self.graphicsView.plot(self.x, self.y5, pen=pen5)
        self.graphicsView.plot(self.x, self.y6, pen=pen6)
        self.graphicsView.plot(self.x, self.y7, pen=pen7)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Overview = QtWidgets.QMainWindow()
    ui = Ui_Overview()
    ui.overviewUi(Overview)
    Overview.show()
    sys.exit(app.exec_())
